modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = ""
license = "ARR"

[[mods]]
modId = "dlssmc"
version = "0.3.0"
displayName = "Frame Generation"
authors = "桃"
description = '''
为 Minecraft 接入帧生成：当前后端是 NVIDIA DLSS-G，规划中加入 AMD FSR；另带 DLSS 超分。
不改动光影管线本身，依赖 Embeddium + Oculus。
'''

[[dependencies.dlssmc]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.dlssmc]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.20.2)"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.dlssmc]]
    modId = "embeddium"
    mandatory = true
    versionRange = "*"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.dlssmc]]
    modId = "oculus"
    mandatory = true
    versionRange = "*"
    ordering = "NONE"
    side = "CLIENT"
